export const TMDB_API_KEY = 'a873f0f2150513d86b80492c6c226d40';
export const TMDB_BASE_URL = 'https://api.themoviedb.org/3/search/movie?api_key=a873f0f2150513d86b80492c6c226d40&language=en-US&page=1&include_adult=false&query=';
export const TMDB_BASE_IMG = 'https://image.tmdb.org/t/p/w1280';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOAD_MOVIES_API = 'LOAD_MOVIES_API';
export const LOAD_MOVIES_API_PENDING = 'LOAD_MOVIES_API_PENDING';
export const LOAD_MOVIES_API_FULFILLED = 'LOAD_MOVIES_API_FULFILLED';
export const LOAD_MOVIES_API_REJECTED = 'LOAD_MOVIES_API_REJECTED';
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
export const LOGOUT = 'LOGOUT';
export const CREATE_TOP10_MOVIE_REF = 'CREATE_TOP10_MOVIE_REF';
export const LOAD_MOVIES_FROM_DB = 'LOAD_MOVIES_FROM_DB';
export const ADD_TOP10_MOVIE = 'ADD_TOP10_MOVIE';
export const DELETE_TOP10_MOVIE ='DELETE_TOP10_MOVIE';